# Generated by Django 2.1.5 on 2019-03-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0002_auto_20190311_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='expense_type_id',
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='Activity_log_type',
            field=models.CharField(choices=[('traffic_offence', 'Traffic_offence'), ('breakdown', 'Breakdown'), ('repair', 'Repair'), ('fuel', 'Fuel'), ('milage', 'Milage'), ('others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='crew',
            name='driver_license_type',
            field=models.CharField(choices=[('category_a', 'Category_A'), ('category_b', 'Category_B'), ('category_c', 'Category_C')], max_length=100),
        ),
        migrations.AlterField(
            model_name='matatu',
            name='route',
            field=models.CharField(choices=[('eldoret', 'Eldoret'), ('karatina', 'Karatina'), ('nairobi', 'Nairobi'), ('nanyuki', 'Nanyuki'), ('nakuru', 'Nakuru'), ('nyeri', 'Nyeri'), ('thika', 'Thika')], max_length=100),
        ),
        migrations.DeleteModel(
            name='ExpenseType',
        ),
    ]
